
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'AB53DEEF92510B131311E0FD12692F26'
    
_lr_action_items = {'(':([0,1,4,7,8,9,10,11,],[1,1,1,1,1,1,1,1,]),'<':([2,5,6,12,13,14,15,16,17,18,],[7,-9,7,-7,-8,-2,-5,-3,-6,-4,]),'+':([2,5,6,12,13,14,15,16,17,18,],[8,-9,8,-7,-8,8,-5,8,-6,-4,]),'-':([0,1,4,7,8,9,10,11,],[4,4,4,4,4,4,4,4,]),'>':([2,5,6,12,13,14,15,16,17,18,],[9,-9,9,-7,-8,9,-5,-3,-6,-4,]),'|':([2,5,6,12,13,14,15,16,17,18,],[11,-9,11,-7,-8,11,-5,11,-6,-4,]),'&':([2,5,6,12,13,14,15,16,17,18,],[10,-9,10,-7,-8,10,10,10,-6,10,]),'$end':([2,3,5,12,13,14,15,16,17,18,],[-1,0,-9,-7,-8,-2,-5,-3,-6,-4,]),'NUMBER':([0,1,4,7,8,9,10,11,],[5,5,5,5,5,5,5,5,]),')':([5,6,12,13,14,15,16,17,18,],[-9,13,-7,-8,-2,-5,-3,-6,-4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,1,4,7,8,9,10,11,],[2,6,12,14,15,16,17,18,]),'statement':([0,],[3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> expression','statement',1,'p_statement_expr','main.py',47),
  ('expression -> expression < expression','expression',3,'p_expression_binop','main.py',52),
  ('expression -> expression > expression','expression',3,'p_expression_binop','main.py',53),
  ('expression -> expression | expression','expression',3,'p_expression_binop','main.py',54),
  ('expression -> expression + expression','expression',3,'p_expression_binop','main.py',55),
  ('expression -> expression & expression','expression',3,'p_expression_binop','main.py',56),
  ('expression -> - expression','expression',2,'p_expression_uminus','main.py',70),
  ('expression -> ( expression )','expression',3,'p_expression_group','main.py',75),
  ('expression -> NUMBER','expression',1,'p_expression_number','main.py',80),
]
